name: todo_list
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  sqflite: ^2.0.2
  path: ^1.8.0
  google_fonts: ^2.3.1
  flutter_signin_button: ^2.0.0
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  validatorless: ^1.2.1
  flutter_overlay_loader: ^1.0.3
  google_sign_in: ^5.0.4
  date_picker_timeline: ^1.2.3
  intl: ^0.17.0
  animated_toggle_switch: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: TodoListicons.ttf
      fonts:
        - asset: assets/fonts/TodoListicons.ttf

